### ISSUE TITLE
[GoogleMapコンポーネント]住所入力フォーム作る

### ISSUE THREAD

**Issue by hihumikan** [furukawaTakumi/Hack-U-vol3#4]
Google Map コンポーネントに追加するフォーム
入力すると、Gmapの表示が住所位置に移動する

**Comment by hihumikan** [comment]
https://developers.google.com/maps/documentation/geocoding/overview

**Comment by hihumikan** [comment]
https://github.com/googlemaps/js-samples/tree/6522a4a3fbfe5b0eac1cdae4bbce4ce6841e40d0

**Comment by hihumikan** [comment]
commit の#4 js ????に上げました。　なんか動作しないです...

**Comment by furukawaTakumi** [comment]
ブランチが上がっていないのでみようと思ったけど見れないですす

**Comment by furukawaTakumi** [comment]
@hihumikan 僕も今日の夜嵌って気づいたんだけど、APIタイプのやつはブラウザから利用しようとしてもCORSで利用できないようになってて、これはどうも単純には避けようがないものみたい。ブラウザからgoogle mapのライブラリを利用する時には、〜serviceってやつを使うのが普通ということに気づいたので、したのやつを今一度見て欲しい。

https://developers.google.com/maps/documentation/javascript/geocoding

**Comment by furukawaTakumi** [comment]
fixしたのでクローズ
